"""Tests for the LangGraph campaign agent and tools.

Tests agent routing, tool invocation, error handling, and multi-step flows
using mocked LLM and RAG services.
"""

from __future__ import annotations

import json
from unittest.mock import AsyncMock, patch

import pytest


# ── Tool unit tests ───────────────────────────────────────────────────


class TestQueryCampaignDataTool:
    """Tests for the query_campaign_data tool."""

    @pytest.mark.asyncio
    async def test_rejects_non_select_query(self, mock_llm):
        """Tool should reject non-SELECT queries generated by the LLM."""
        from app.agents.tools import _execute_readonly_sql

        with pytest.raises(ValueError, match="Only SELECT"):
            await _execute_readonly_sql("DROP TABLE campaigns")

    @pytest.mark.asyncio
    async def test_rejects_delete_query(self, mock_llm):
        """Tool should reject DELETE queries."""
        from app.agents.tools import _execute_readonly_sql

        with pytest.raises(ValueError, match="Only SELECT"):
            await _execute_readonly_sql("DELETE FROM campaigns WHERE id = 1")

    @pytest.mark.asyncio
    async def test_rejects_update_query(self, mock_llm):
        """Tool should reject UPDATE queries."""
        from app.agents.tools import _execute_readonly_sql

        with pytest.raises(ValueError, match="Only SELECT"):
            await _execute_readonly_sql("UPDATE campaigns SET status = 'active'")

    def test_serialize_row_handles_dates(self):
        """Row serializer should convert dates to ISO strings."""
        from datetime import date, datetime

        from app.agents.tools import _serialize_row

        row = {
            "name": "test",
            "start": date(2025, 1, 1),
            "ts": datetime(2025, 1, 1, 12, 0),
        }
        result = _serialize_row(row)
        assert result["start"] == "2025-01-01"
        assert "2025-01-01" in result["ts"]

    def test_serialize_row_handles_uuid(self):
        """Row serializer should convert UUIDs to strings."""
        import uuid

        from app.agents.tools import _serialize_row

        test_uuid = uuid.uuid4()
        row = {"id": test_uuid, "name": "test"}
        result = _serialize_row(row)
        assert result["id"] == str(test_uuid)


class TestSearchSimilarTool:
    """Tests for the search_similar_campaigns tool."""

    @pytest.mark.asyncio
    async def test_returns_json_on_success(self, mock_rag):
        """Tool should return JSON with campaigns list."""
        with patch("app.agents.tools.get_rag_service", return_value=mock_rag):
            from app.agents.tools import search_similar_campaigns

            result = await search_similar_campaigns.ainvoke(
                {"query": "high-performing QSR campaigns"}
            )
            parsed = json.loads(result)
            assert "campaigns" in parsed
            assert parsed["count"] >= 1
            assert (
                parsed["campaigns"][0]["campaign_name"]
                == "Dunkin' Q4 Holiday Favorites"
            )

    @pytest.mark.asyncio
    async def test_includes_similarity_score(self, mock_rag):
        """Results should include similarity scores."""
        with patch("app.agents.tools.get_rag_service", return_value=mock_rag):
            from app.agents.tools import search_similar_campaigns

            result = await search_similar_campaigns.ainvoke({"query": "test"})
            parsed = json.loads(result)
            assert "similarity_score" in parsed["campaigns"][0]

    @pytest.mark.asyncio
    async def test_handles_empty_results(self):
        """Tool should handle empty search results gracefully."""
        empty_rag = AsyncMock()
        empty_rag.retrieve = AsyncMock(return_value=[])

        with patch("app.agents.tools.get_rag_service", return_value=empty_rag):
            from app.agents.tools import search_similar_campaigns

            result = await search_similar_campaigns.ainvoke({"query": "nonexistent"})
            parsed = json.loads(result)
            assert parsed["count"] == 0


class TestCompareCampaignsTool:
    """Tests for the compare_campaigns tool."""

    @pytest.mark.asyncio
    async def test_returns_error_for_missing_campaign(self, mock_llm):
        """Should return error JSON when campaign not found."""
        with (
            patch("app.agents.tools.get_llm_client", return_value=mock_llm),
            patch(
                "app.agents.tools._fetch_campaign_with_metrics",
                side_effect=[None, {"campaign_name": "test"}],
            ),
        ):
            from app.agents.tools import compare_campaigns

            result = await compare_campaigns.ainvoke(
                {"campaign_id_1": 999, "campaign_id_2": 1}
            )
            parsed = json.loads(result)
            assert "error" in parsed
            assert "999" in parsed["error"]


class TestRecommendAudienceTool:
    """Tests for the recommend_audience tool."""

    @pytest.mark.asyncio
    async def test_handles_rag_failure_gracefully(self):
        """Tool should return error JSON if RAG fails."""
        failing_rag = AsyncMock()
        failing_rag.retrieve = AsyncMock(side_effect=Exception("ChromaDB down"))

        with patch("app.agents.tools.get_rag_service", return_value=failing_rag):
            from app.agents.tools import recommend_audience

            result = await recommend_audience.ainvoke({"description": "test audience"})
            parsed = json.loads(result)
            assert "error" in parsed


# ── Agent graph structure tests ───────────────────────────────────────


class TestAgentGraph:
    """Tests for the LangGraph agent structure."""

    def test_graph_compiles(self):
        """Agent graph should compile without errors."""
        from app.agents.campaign_agent import build_graph

        graph = build_graph()
        compiled = graph.compile()
        assert compiled is not None

    def test_graph_has_required_nodes(self):
        """Graph should contain all expected nodes."""
        from app.agents.campaign_agent import build_graph

        graph = build_graph()
        node_names = set(graph.nodes.keys())
        assert "router" in node_names
        assert "tool_executor" in node_names
        assert "synthesizer" in node_names
        assert "error_handler" in node_names

    def test_all_tools_registered(self):
        """ALL_TOOLS should contain all 5 defined tools."""
        from app.agents.tools import ALL_TOOLS

        tool_names = {t.name for t in ALL_TOOLS}
        assert "query_campaign_data" in tool_names
        assert "search_similar_campaigns" in tool_names
        assert "compare_campaigns" in tool_names
        assert "generate_lci_report" in tool_names
        assert "recommend_audience" in tool_names
        assert len(ALL_TOOLS) == 5


# ── Agent routing tests (mocked LLM) ─────────────────────────────────


class TestAgentRouting:
    """Tests for agent routing decisions."""

    def test_route_after_router_detects_tool_calls(self):
        """Router should route to tool_executor when LLM returns tool calls."""
        from unittest.mock import MagicMock

        from langchain_core.messages import AIMessage

        from app.agents.campaign_agent import route_after_router

        # Simulate an AI message with tool calls
        msg = MagicMock(spec=AIMessage)
        msg.tool_calls = [{"name": "query_campaign_data", "args": {}, "id": "1"}]

        state = {"messages": [msg], "error_count": 0}
        assert route_after_router(state) == "tool_executor"

    def test_route_after_router_goes_to_synthesizer_without_tools(self):
        """Router should route to synthesizer when no tool calls."""
        from langchain_core.messages import AIMessage

        from app.agents.campaign_agent import route_after_router

        msg = AIMessage(content="Here is your answer.")
        state = {"messages": [msg], "error_count": 0}
        assert route_after_router(state) == "synthesizer"

    def test_route_after_router_handles_error_limit(self):
        """Router should route to error_handler when error count exceeds max."""
        from langchain_core.messages import AIMessage

        from app.agents.campaign_agent import route_after_router

        msg = AIMessage(content="")
        state = {"messages": [msg], "error_count": 5}
        assert route_after_router(state) == "error_handler"

    def test_error_handler_retries_under_limit(self):
        """Error handler should route back to router when under retry limit."""
        from app.agents.campaign_agent import route_after_error

        state = {"error_count": 1}
        assert route_after_error(state) == "router"

    def test_error_handler_gives_up_over_limit(self):
        """Error handler should route to END when over retry limit."""
        from app.agents.campaign_agent import route_after_error

        state = {"error_count": 5}
        assert route_after_error(state) == "__end__"


# ── Agent invoke convenience method ──────────────────────────────────


class TestAgentInvoke:
    """Tests for the invoke_agent convenience method."""

    @pytest.mark.asyncio
    async def test_invoke_returns_dict_with_required_keys(self):
        """invoke_agent should always return dict with reply, sources, data."""
        # Mock the compiled graph to avoid needing real LLM
        mock_result = {
            "messages": [],
            "campaign_context": "",
            "current_tool_results": "",
            "report_data": "",
            "error_count": 0,
        }

        with patch("app.agents.campaign_agent.compiled_graph") as mock_graph:
            from langchain_core.messages import AIMessage

            mock_result["messages"] = [AIMessage(content="Test response")]
            mock_graph.ainvoke = AsyncMock(return_value=mock_result)

            from app.agents.campaign_agent import invoke_agent

            result = await invoke_agent("test query")

            assert "reply" in result
            assert "sources" in result
            assert "data" in result
            assert result["reply"] == "Test response"

    @pytest.mark.asyncio
    async def test_invoke_handles_exception_gracefully(self):
        """invoke_agent should return error message, never raise."""
        with patch("app.agents.campaign_agent.compiled_graph") as mock_graph:
            mock_graph.ainvoke = AsyncMock(side_effect=Exception("LLM exploded"))

            from app.agents.campaign_agent import invoke_agent

            result = await invoke_agent("test query")

            assert "reply" in result
            assert (
                "error" in result["reply"].lower() or "sorry" in result["reply"].lower()
            )
            assert result["sources"] == []
