"""Pydantic models for API request/response validation and structured LLM output.

Schemas:
    API layer — ChatRequest, ChatResponse, ReportResponse, HealthResponse.
    LLM structured output — CampaignSummary, ReportContent, AudienceRecommendation.
"""

from datetime import date, datetime

from pydantic import BaseModel, Field

from app.models.campaign import CampaignStatus


# ---------------------------------------------------------------------------
# API request / response schemas
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    """Incoming chat message from the user."""

    message: str = Field(..., min_length=1, description="User's natural-language query.")
    session_id: str | None = Field(None, description="Optional conversation session ID.")


class ChatResponse(BaseModel):
    """Response returned from the /chat endpoint."""

    reply: str = Field(..., description="Agent's natural-language response.")
    sources: list[str] = Field(default_factory=list, description="Source references used.")


class CampaignOut(BaseModel):
    """Campaign data returned by the API."""

    id: int
    name: str
    status: CampaignStatus
    budget: float
    start_date: date
    end_date: date | None = None

    model_config = {"from_attributes": True}


class MetricsOut(BaseModel):
    """Campaign metrics returned by the API."""

    date: date
    impressions: int
    clicks: int
    conversions: int
    spend: float
    revenue: float
    ctr: float
    cpa: float
    roas: float


class ReportResponse(BaseModel):
    """Metadata for a generated report."""

    report_id: str
    campaign_id: int
    generated_at: datetime
    download_url: str


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = "ok"
    version: str = "0.1.0"


# ---------------------------------------------------------------------------
# Structured LLM output schemas
# ---------------------------------------------------------------------------


class CampaignSummary(BaseModel):
    """Structured summary of a campaign's performance, produced by the LLM."""

    campaign_name: str
    overall_assessment: str = Field(
        ..., description="One-paragraph performance assessment."
    )
    key_metrics: dict[str, float] = Field(
        ..., description="Headline metrics (CTR, CPA, ROAS, etc.)."
    )
    strengths: list[str]
    weaknesses: list[str]
    recommendations: list[str]


class ReportContent(BaseModel):
    """Full report content generated by the LLM for PDF rendering."""

    title: str
    executive_summary: str
    sections: list[dict[str, str]] = Field(
        ..., description="List of {heading, body} section dicts."
    )
    conclusion: str


class AudienceRecommendation(BaseModel):
    """LLM-generated audience segment recommendation."""

    segment_name: str
    rationale: str
    estimated_reach: int
    confidence: float = Field(..., ge=0.0, le=1.0)
